stages:
  - build
  - deploy

build:
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
  stage: build
  script:
    - yarn && yarn build
  artifacts:
    paths:
      - build
  only:
    - ci-cd
  tags:
    - nodejs


deploy:
  stage: deploy
  cache:
    key: ${CI_JOB_NAME}
    paths:
    - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm i @cloudflare/wrangler -g
    - npm run wrangler publish
  only:
    - ci-cd
  tags:
    - nodejs